// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bimonetary.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NetCoreKit.Samples.BiMonetaryApi.Rpc {
  public static partial class ExchangeService
  {
    static readonly string __ServiceName = "BiMonetary.ExchangeService";

    static readonly grpc::Marshaller<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest> __Marshaller_BiMonetary_TokenRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse> __Marshaller_BiMonetary_TokenResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse> __Marshaller_BiMonetary_PingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest, global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse> __Method_GetTokenInfo = new grpc::Method<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest, global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTokenInfo",
        __Marshaller_BiMonetary_TokenRequest,
        __Marshaller_BiMonetary_TokenResponse);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse> __Method_Ping = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_BiMonetary_PingResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NetCoreKit.Samples.BiMonetaryApi.Rpc.BimonetaryReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ExchangeService</summary>
    public abstract partial class ExchangeServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse> GetTokenInfo(global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse> Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ExchangeService</summary>
    public partial class ExchangeServiceClient : grpc::ClientBase<ExchangeServiceClient>
    {
      /// <summary>Creates a new client for ExchangeService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ExchangeServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ExchangeService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ExchangeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ExchangeServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ExchangeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse GetTokenInfo(global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTokenInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse GetTokenInfo(global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTokenInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse> GetTokenInfoAsync(global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTokenInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenResponse> GetTokenInfoAsync(global::NetCoreKit.Samples.BiMonetaryApi.Rpc.TokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTokenInfo, null, options, request);
      }
      public virtual global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse Ping(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse> PingAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NetCoreKit.Samples.BiMonetaryApi.Rpc.PingResponse> PingAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ExchangeServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ExchangeServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ExchangeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetTokenInfo, serviceImpl.GetTokenInfo)
          .AddMethod(__Method_Ping, serviceImpl.Ping).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ExchangeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetTokenInfo, serviceImpl.GetTokenInfo);
      serviceBinder.AddMethod(__Method_Ping, serviceImpl.Ping);
    }

  }
}
#endregion
